/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.magikbyte.samlldoode.meeting.views;

import com.magikbyte.samlldoode.meeting.model.Groupe;
import com.magikbyte.samlldoode.meeting.model.Agent;
import com.magikbyte.samlldoode.meeting.utils.SearchUtils;
import com.toedter.calendar.JDateChooser;
import java.awt.FlowLayout;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yirou
 */
public class ConnetedView extends javax.swing.JFrame implements Observer {

    Agent user;
    Groupe groupe;
    ManagerView managerView;
    JDateChooser dateProposeParAdminChooser;
    JDateChooser dateProposeParLesAgentsChooser;
    int counterDateMessage = 0;

    /**
     * Creates new form ConnetedView
     * @param grp
     * @param user
     */
    public ConnetedView(String grp, String user, ManagerView managerView) {
        initComponents();
        setResizable(false);
        this.managerView = managerView;
        this.user = SearchUtils.findUser(user);
        userNameTxt.setText(this.user.getName());
        this.groupe = SearchUtils.findGroupe(grp);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        jPanel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        proposePanelDate.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        dateProposeParAdminChooser = new JDateChooser();
        dateProposeParLesAgentsChooser = new JDateChooser();
        jPanel2.add(dateProposeParAdminChooser);
        proposePanelDate.add(dateProposeParLesAgentsChooser);
        checkAccess();
    }

    private void initPaneldate() {

    }

    public void setManagerView(ManagerView managerView) {
        this.managerView = managerView;
    }

    public ManagerView getManagerView() {
        return managerView;
    }

    private void checkAccess() {
        if (user.isOnline()) {
            JOptionPane.showMessageDialog(null, "Utilisateur dejà connecté");
        } else {
            acceptConnexion();
            disableDateButon();
        }

    }

    private void acceptConnexion() {
        this.setVisible(true);
        user.setOnline(true);
        this.user.setCurrentGroupe(groupe);
        groupe.addObserver(this);
        this.user.init();
        user.connectToGroupeTopic();
        this.groupe.getUsers().add(user);
        this.groupe.getTimer().addObserver(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDate = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        msgTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMsg = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        proposedDateTxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        timerTxt = new javax.swing.JLabel();
        userNameTxt = new javax.swing.JLabel();
        proposePanelDate = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelDate.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton3.setText("Calculer le resultat");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDateLayout = new javax.swing.GroupLayout(panelDate);
        panelDate.setLayout(panelDateLayout);
        panelDateLayout.setHorizontalGroup(
            panelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelDateLayout.setVerticalGroup(
            panelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDateLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        msgTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgTxtActionPerformed(evt);
            }
        });

        jButton1.setText("Ajouter date");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        listMsg.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Coucou" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listMsg);

        jLabel2.setFont(new java.awt.Font("URW Chancery L", 3, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 89, 168));
        jLabel2.setText("your message");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        proposedDateTxt.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        proposedDateTxt.setForeground(new java.awt.Color(29, 155, 228));
        proposedDateTxt.setText("jLabel1");

        jLabel1.setText("Dates possibles");

        jLabel3.setText("Temps restant:");

        timerTxt.setText(".");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(proposedDateTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(184, 184, 184)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(timerTxt)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(timerTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(proposedDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        userNameTxt.setText("jLabel1");

        proposePanelDate.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout proposePanelDateLayout = new javax.swing.GroupLayout(proposePanelDate);
        proposePanelDate.setLayout(proposePanelDateLayout);
        proposePanelDateLayout.setHorizontalGroup(
            proposePanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );
        proposePanelDateLayout.setVerticalGroup(
            proposePanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton2.setText("Ajouter date");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setText("Admin, dates possibles");

        jLabel5.setText("Agent, date disponible");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(104, 104, 104))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(proposePanelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(292, 292, 292)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(userNameTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                            .addComponent(msgTxt))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userNameTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(msgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(proposePanelDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jButton1)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void msgTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgTxtActionPerformed
        String msg = "msg," + user.getName() + " >> " + msgTxt.getText();
        msgTxt.setText("");
        user.sendMsgToTopic(msg);
    }//GEN-LAST:event_msgTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (dateProposeParAdminChooser.getDate() != null) {
            SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
            Date d = dateProposeParAdminChooser.getDate();
            String msg = "dateAdmin," + user.getName() + " , " + formatter.format(d);
            user.sendMsgToTopic(msg);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (dateProposeParLesAgentsChooser.getDate() != null && counterDateMessage < 3) {
            SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
            Date d = dateProposeParLesAgentsChooser.getDate();
            String msg = "dateUser," + user.getName() + " , " + formatter.format(d);
            user.sendMsgToTopic(msg);
            counterDateMessage++;
        } else {
            JOptionPane.showMessageDialog(null, "Vous avez atteint le nombre maximum de proposition");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Map<String, Integer> result = new HashMap<>();
        List<String> userProposition;
        for (String key : groupe.getDateProposeParLesAgents().keySet()) {
            userProposition = groupe.getDateProposeParLesAgents().get(key);
            for (String date : userProposition) {
                if (result.get(date) == null) {
                    result.put(date, 1);
                } else {
                    int occurence = result.get(date);
                    occurence++;
                    result.put(date, occurence);
                }
            }
        }

        String dateRetenue = findMax(result);
        String msg = "msg," + user.getName() + " >> Date retenue : " + dateRetenue;
        user.sendMsgToTopic(msg);


    }//GEN-LAST:event_jButton3ActionPerformed
    private String findMax(Map<String, Integer> result) {
        int max = 0;
        String date = "";
        for (String key : result.keySet()) {
            if (result.get(key) > max) {
                max = result.get(key);
                date = key;
            }
        }
        return date;
    }

    @Override
    public void update(Observable o, Object arg) {
        if (o instanceof Groupe) {
            System.out.println("update msg");
            displayMsgs();
            displayDates();
        } else if (this.groupe.getTimer().isAlive()) {
            timerTxt.setText(this.groupe.getDeadLine() + " s");
        } else {
//            JOptionPane.showMessageDialog(null, "Fin de proposition de dates");
            disableDateButon();
        }
    }

    private void disableDateButon() {
        if (!this.groupe.getTimer().isAlive()) {
            dateProposeParLesAgentsChooser.setEnabled(false);
            jButton2.setEnabled(false);
        }
        if (!this.groupe.getAdmin().equals(user)) {
            dateProposeParAdminChooser.setEnabled(false);
            jButton1.setEnabled(false);
        }

    }

    private void displayDates() {
        StringBuilder msg = new StringBuilder();
        List<String> dateUser;
        String[] column = {"User", "Date1", "Date2", "Date3"};
        jTable1.setModel(new DefaultTableModel(column, groupe.getDateProposeParLesAgents().size()));
        for (String m : this.groupe.getDateProposeParAdmin()) {
            msg.append(m + " | ");
        }
        proposedDateTxt.setText(msg.toString());

        for (Agent u : groupe.getUsers()) {
            dateUser = this.groupe.getDateProposeParLesAgents().get(u.getName());
            if (dateUser != null) {
                displayInTable(u, dateUser);
            }

        }

    }

    private void displayInTable(Agent u, List<String> dateUser) {
        int line = u.getId() - 1;
        jTable1.setValueAt(u.getName(), line, 0);
        for (int i = 0; i < dateUser.size(); i++) {
            jTable1.setValueAt(dateUser.get(i), line, i + 1);
        }
    }

    private String[] objectListToStringArray(List<?> liste, String toDelete) {
        String[] result = new String[liste.size()];
        for (int i = 0; i < liste.size(); i++) {
            String msg = liste.get(i).toString();
            if (msg.startsWith(toDelete)) {

                result[i] = msg.replace(toDelete, "");
            }

        }
        return result;
    }

    private void displayMsgs() {
        String[] msg = objectListToStringArray(groupe.getMessages(), "msg,");
        listMsg.setListData(msg);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> listMsg;
    private javax.swing.JTextField msgTxt;
    private javax.swing.JPanel panelDate;
    private javax.swing.JPanel proposePanelDate;
    private javax.swing.JLabel proposedDateTxt;
    private javax.swing.JLabel timerTxt;
    private javax.swing.JLabel userNameTxt;
    // End of variables declaration//GEN-END:variables
@Override
    protected void processWindowEvent(WindowEvent we) {
        if (WindowEvent.WINDOW_CLOSING == we.getID()) {
            groupe.deleteObserver(this);
            this.dispose();
            user.logout();

        }

    }

}
